  - platform: sql
    db_url: mysql://homeassistant:chah6viCaapeeD@mysql.serverhome.home:3306/homeassistant?charset=utf8mb4
    queries:
      - name: DB size
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB