title: Тестовая
icon: mdi:ab-testing
cards:
  - type: vertical-stack
    cards:
      - type: markdown
        content: >
            **все подряд**
      - type: horizontal-stack
        cards:
            - type: 'custom:vacuum-card'
              entity: vacuum.xiaomi_vacuum_cleaner_1s
              stats:
                default:
                  - attribute: filter_left
                    unit: hours
                    subtitle: Filter
                  - attribute: side_brush_left
                    unit: hours
                    subtitle: Side brush
                  - attribute: main_brush_left
                    unit: hours
                    subtitle: Main brush
                  - attribute: sensor_dirty_left
                    unit: hours
                    subtitle: Sensors
                cleaning:
                  - attribute: cleaned_area
                    unit: m2
                    subtitle: Cleaning area
                  - attribute: cleaning_time
                    unit: minutes
                    subtitle: Cleaning time