{
 "title": "rocketchat",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "deployment", "label": "deployment", "query": { "query": "nodejs_active_handles_total" } }
  ]
 },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users Online",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_users_online)" }
     ]
    },
    {
     "title": "Users Away",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_users_away)" }
     ]
    },
    {
     "title": "DDP Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users)"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_users_total)" }
     ]
    },
    {
     "title": "Rooms",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_rooms_total)" }
     ]
    },
    {
     "title": "Messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "max(rocketchat_messages_total)" }
     ]
    },
    {
     "title": "Users Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      { "expr": "max(rocketchat_users_total)" }
     ]
    },
    {
     "title": "Rooms  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      { "expr": "max(rocketchat_rooms_total)" }
     ]
    },
    {
     "title": "Messages  Diff",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      { "expr": "max(rocketchat_messages_total)" }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metrics Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(rocketchat_metrics_requests[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metrics Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "rocketchat_metrics_size", "legendFormat": "{{instance}}" }
     ]
    }
   ]
  },
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Handles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_active_handles_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Active Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_active_requests_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Event loop lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Heap used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (space) (nodejs_heap_size_used_bytes)",
       "legendFormat": "{{space}}"
      }
     ]
    },
    {
     "title": "Per pod heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{instance}} [{{space}}]" }
     ]
    },
    {
     "title": "GC - Seconds Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_pause_seconds_total[5m])) by (gctype)",
       "legendFormat": "{{gctype}}"
      }
     ]
    },
    {
     "title": "GC - Bytes Freed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(nodejs_gc_reclaimed_bytes_total[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DDP Rate Limiter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Limit by userId",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_ddp_rate_limit_exceeded[5m])) by (user_id)",
       "legendFormat": "{{user_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RocketChat Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages Sent (30m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(rocketchat_message_sent[30m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Messages Sent Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "max(rocketchat_messages_total)", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Users Presence",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "avg(rocketchat_users_online)", "legendFormat": "Online" },
      { "expr": "avg(rocketchat_users_away)", "legendFormat": "Away" }
     ]
    },
    {
     "title": "Users & Sessions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_ddp_connected_users)",
       "legendFormat": "Connected Users"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_count)",
       "legendFormat": "All Sessions"
      },
      {
       "expr": "sum(rocketchat_ddp_sessions_auth)",
       "legendFormat": "Authenticated Sessions "
      }
     ]
    },
    {
     "title": "Web Socket Connections per pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rocketchat_ddp_connected_users", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Apps Installed / Disabled / Failed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rocketchat_apps_installed", "legendFormat": "{{instance}} - installed" },
      { "expr": "rocketchat_apps_enabled", "legendFormat": "{{instance}} - enabled" },
      { "expr": "rocketchat_apps_failed", "legendFormat": "{{instance}} - failed" }
     ]
    },
    {
     "title": "Oplog",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(increase(rocketchat_oplog[5m])) by (collection,op)",
       "legendFormat": "{{collection}}/{{op}}"
      }
     ]
    },
    {
     "title": "Oplog By instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(increase(rocketchat_oplog[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Oplog Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rocketchat_oplog_queue", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Push Queue",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "rocketchat_push_queue", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Meteor Facts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_facts) by (pkg, fact)",
       "legendFormat": "{{pkg}} {{fact}}"
      }
     ]
    },
    {
     "title": "Total of Users",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      { "expr": "max(rocketchat_users_total)", "legendFormat": "Users" }
     ]
    },
    {
     "title": "Total of Rooms",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      { "expr": "max(rocketchat_rooms_total)", "legendFormat": "Rooms" }
     ]
    },
    {
     "title": "Notifications / Minute",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_notification_sent[5m])) by (notification_type)",
       "legendFormat": "{{notification_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Methods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Methods Total Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method) * sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_methods) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Meteor Methods Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_methods_count[5m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Meteor Subscription Total Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription) * sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_meteor_subscriptions) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    },
    {
     "title": "Meteor Subscription Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_meteor_subscriptions_count[5m])) by (subscription)",
       "legendFormat": "{{subscription}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Callbacks & Hooks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Callbacks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_callbacks) by (callback) * sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_callbacks[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Callbacks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_callbacks_count[5m])) by (callback)",
       "legendFormat": "{{callback}}"
      }
     ]
    },
    {
     "title": "Hooks Total Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_hooks) by (hook) * sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_hooks[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    },
    {
     "title": "Hooks Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_hooks_count[5m])) by (hook)",
       "legendFormat": "{{hook}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "REST API Total Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rocketchat_rest_api) by (entrypoint) * sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(rocketchat_rest_api[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    },
    {
     "title": "REST API Calls / Minute",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(rocketchat_rest_api_count[5m])) by (entrypoint)",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  }
 ]
}