  - platform: template
    sensors:
      humidifier_1_humidity:
        value_template: "{{ state_attr('fan.humidifier_1', 'humidity') }}"
        unit_of_measurement: '%'
        device_class: humidity
        friendly_name: 'Увлажнитель влажность'