  - platform: template
    sensors:
      humidifier_1_temperature:
        value_template: "{{ state_attr('fan.humidifier_1', 'temperature') }}"
        unit_of_measurement: '°C'
        device_class: temperature
        friendly_name: 'Увлажнитель температура'