homeassistant:
  name: homeassistant
  latitude: 55.753995
  longitude: 37.614069
  elevation: 120
  unit_system: metric
  time_zone: Europe/Moscow
  packages: !include_dir_merge_named blocks/packages

# Ручная конфигурация
# Отображение панели настроек в интерфейсе
config:
# Сканирование доступных устройств в сети
ssdp:
# Включение карты
map:
# Включение поддержки приложения
mobile_app:
# Отслеживание солнца
sun:
# API для предоставления информации о системе и ее компонентах
system_health:
# Сенсор для отображения последней версии НА
updater:
# Потоковое изображение с камер
stream:
# Включение истории
history:
# Включение журнала
logbook:

lovelace:
  mode: yaml
  resources:
   - url: /local/vacuum-card.js # https://github.com/denysdovhan/vacuum-card/releases/tag/v1.17.0
     type: module
   - url: /local/mini-humidifier-bundle.js # https://github.com/artem-sedykh/mini-humidifier/releases/tag/v2.3.2
     type: module

# Text to speech
tts:
  - platform: google_translate

# Читай эти блоки из других файлов
recorder: !include blocks/recorder.yaml # База данных
vacuum: !include blocks/vacuum.yaml # Пылесосы
fan: !include blocks/fan.yaml # Увлажнители

# Читай эти блоки из других файлов (весь каталог)
automation: !include_dir_merge_list blocks/automation
sensor: !include_dir_merge_list blocks/sensors # Сенсоры