title: Главная
icon: mdi:home-assistant
cards:

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Текущее состояние**

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-month

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.db_size
              name: Размер базы данных homeassistant
              icon: mdi:database

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Графики**

        - type: horizontal-stack
          cards:
          - type: gauge
            name: Загрузка CPU
            unit: '%'
            entity: sensor.processor_use
            severity:
              green: 0
              yellow: 60
              red: 85

          - type: gauge
            name: Загрузка ОЗУ
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

        - type: horizontal-stack
          cards:
          - type: gauge
            name: Заполнен системный диск
            unit: '%'
            entity: sensor.disk_use_percent
            severity:
              green: 0
              yellow: 60
              red: 85

          - type: gauge
            name: Свободно на системном диске
            unit: 'Гб'
            entity: sensor.disk_free
            severity:
              green: 100
              yellow: 60
              red: 20

        - type: history-graph
          entities:
            - entity: sensor.db_size
              name: Размер базы данных homeassistant