title: Датчики
icon: mdi:leak
cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.sensor_leak_vanna_water_leak
                    name: Протечка

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: sensor.smartmi_evaporative_humidifier_humidity
                  - entity: binary_sensor.sensor_leak_vanna_battery_low
                  - entity: sensor.smartmi_evaporative_humidifier_temperature