title: Погода в доме
icon: mdi:home-thermometer-outline
cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: fan.humidifier_1
                    name: Увлажнитель

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-humidifier
                entity: fan.humidifier_1
                model: 'zhimi.humidifier.cb1'