homeassistant:
  name: homeassistant
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include_dir_merge_named blocks/customize
  packages: !include_dir_merge_named blocks/packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: !secret http_password

# Ручная конфигурация
# Отображение панели настроек в интерфейсе
config:
# Сканирование доступных устройств в сети
ssdp:
# Включение карты
map:
# Включение поддержки приложения
mobile_app:
# Отслеживание солнца
sun:
# API для предоставления информации о системе и ее компонентах
system_health:
# Сенсор для отображения последней версии НА
updater:
# Потоковое изображение с камер
stream:
# Включение истории
history:
# Включение журнала
logbook:

lovelace:
  mode: yaml
  resources:
   - url: /local/vacuum-card.js # https://github.com/denysdovhan/vacuum-card/releases/tag/v1.17.0
     type: module
   - url: /local/simple-weather-card-bundle.js # https://github.com/kalkih/simple-weather-card/releases/tag/v0.8.1
     type: module
   - url: /local/mini-humidifier-bundle.js # https://github.com/artem-sedykh/mini-humidifier/releases/tag/v2.3.2
     type: module

# Text to speech
tts:
  - platform: google_translate

# Читай эти блоки из других файлов
recorder: !include blocks/recorder.yaml # База данных
vacuum: !include blocks/vacuum.yaml # Пылесосы
fan: !include blocks/fan.yaml # Увлажнители
api: !include blocks/api.yaml # https://www.home-assistant.io/integrations/api/
mikrotik: !include blocks/mikrotik.yaml # https://www.home-assistant.io/integrations/mikrotik/
homekit: !include blocks/homekit.yaml # https://www.home-assistant.io/integrations/homekit/
input_select: !include blocks/input_select.yaml # https://www.home-assistant.io/integrations/input_select/
device_tracker: !include blocks/device_tracker.yaml # https://www.home-assistant.io/integrations/device_tracker/
notify: !include blocks/notify.yaml # https://www.home-assistant.io/integrations/notify/
mqtt: !include blocks/mqtt.yaml # https://www.home-assistant.io/integrations/mqtt/
prometheus: !include blocks/prometheus.yaml # https://www.home-assistant.io/integrations/prometheus/
group: !include blocks/group.yaml # https://www.home-assistant.io/integrations/group/
script: !include blocks/script.yaml # https://www.home-assistant.io/integrations/script/
scene: !include blocks/scene.yaml # https://www.home-assistant.io/integrations/scene/
webostv: !include blocks/webostv.yaml # https://www.home-assistant.io/integrations/webostv/
telegram_bot: !include blocks/telegram_bot.yaml # https://www.home-assistant.io/integrations/telegram_bot/
weather: !include blocks/weather.yaml # https://www.home-assistant.io/integrations/weather/

# Читай эти блоки из других файлов (весь каталог)
automation: !include_dir_merge_list blocks/automation
sensor: !include_dir_merge_list blocks/sensor # https://www.home-assistant.io/integrations/sensor/
switch: !include_dir_merge_list blocks/switch # https://www.home-assistant.io/integrations/switch/