{
 "title": "telegraf system",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "SHOW TAG VALUES FROM system WITH KEY=\"host\""
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"diskio\" WITH KEY = \"name\" WHERE host =~ /$hostname/"
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$hostname/"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$hostname/"
   },
   {
    "name": "device",
    "label": "device",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\" WHERE host =~ /$hostname/"
   },
   {
    "name": "sensor",
    "label": "sensor",
    "query": "SHOW TAG VALUES FROM \"temp\" WITH KEY = \"sensor\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  {
   "title": "common",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "сервер",
     "type": "text",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": {
      "content": "<center>\n<img src=\"https://pngimage.net/wp-content/uploads/2018/06/server-logo-png-3.png\" width=\"100\" >\n<br>\n<p><font size=\"10\"> $hostname </font></p>\n</center>\n\n\n\n\n"
     }
    },
    {
     "title": "uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "system",
       "select": [
        [
         { "params": [ "uptime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "cpu usage idle",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*-1 +100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "mem used percent",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "zombies",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "zombies" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "processes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "$device",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 7, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "disk",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "cpu (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/cpu)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage",
     "type": "graph",
     "description": "В системах Linux для сбора данных о загрузке процессора используется файл / proc / stat. Проценты основаны на последних двух выборках\n- system - использования ЦП на уровне системы (ядро Linux)\n- user - использования ЦП на уровне пользователя\n- iowait - загрузки ЦП в режиме ожидания при чтении / записи на диск\n- nice - использования ЦП для пользовательских процессов, помеченных как «хорошо»\n- guest - использования ЦП, потраченного на запуск виртуального процессора\n- guest_nice -\n- idle - использования ЦП во время простоя (без процессов и без ожидания чтения / записи на диск)\n- irq - использования ЦП при обработке аппаратных прерываний\n- softirq - загрузки ЦП, обработка программных прерываний\n- steal - использования ЦП вынуждено ждать, пока гипервизор обрабатывает другие виртуальные процессоры",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "select": [
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_guest" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_guest_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_idle" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_irq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "usage_steal" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "cpu", "operator": "=~", "value": "/^$cpu$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "interrupts (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/interrupts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "soft interrupts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $tag_irq",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "irq" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "soft_interrupts",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "conntrack (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/conntrack)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "conntrack",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "conntrack",
       "select": [
        [
         { "params": [ "ip_conntrack_count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "ip_conntrack_count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "procstat (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/procstat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "process_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "procstat",
       "select": [
        [
         { "params": [ "cpu_usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "cpu_usage" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "system(https://github.com/influxdata/telegraf/tree/master/plugins/inputs/system)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load1" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load5" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "load15" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "mem (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/mem)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "active" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "buffered" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "buffered" ], "type": "alias" }
        ],
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "cached" ], "type": "alias" }
        ],
        [
         { "params": [ "available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "available" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "network (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/net)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_interface: Bytes IN",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "$tag_interface: Bytes OUT",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_interface: IN",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "$tag_interface: OUT",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Netstat",
     "type": "graph",
     "description": "Состояние TCP-соединений и количество сокетов UDP",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Eth0 Drop",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_interface: IN",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "$tag_interface: OUT",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    },
    {
     "title": "Eth0 Error",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_interface: IN",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      },
      {
       "alias": "$tag_interface: OUT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "disk io (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/diskio)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk I/O read/write",
     "type": "graph",
     "description": "Эти значения увеличиваются при завершении запроса ввода-вывода.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_name reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_name writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O read/write bytes",
     "type": "graph",
     "description": "Эти значения подсчитывают количество байтов, прочитанных или записанных в это блочное устройство.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_name read_bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_name write_bytes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O read/write time",
     "type": "graph",
     "description": "Эти значения подсчитывают количество миллисекунд, в течение которых запросы ввода-вывода ожидали на этом блочном устройстве. Если имеется несколько ожидающих запросов ввода-вывода, эти значения будут увеличиваться со скоростью более 1000 в секунду; например, если 60 запросов на чтение ожидают в среднем 30 мс, поле read_time увеличится на 60 * 30 = 1800.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name: read_time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_name: write_time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O io time",
     "type": "graph",
     "description": "Это значение подсчитывает количество миллисекунд, в течение которых устройство помещало в очередь запросы ввода-вывода.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name: io_time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "io_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O weighted io time",
     "type": "graph",
     "description": "Это значение подсчитывает количество миллисекунд, в течение которых запросы ввода-вывода ожидали на этом блочном устройстве. Если имеется несколько ожидающих запросов ввода-вывода, это значение будет увеличиваться как произведение количества миллисекунд на количество ожидающих запросов (см. Read_time выше для примера).",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_name: weighted_io_time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "weighted_io_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O iops in progress",
     "type": "graph",
     "description": "\nЭто значение подсчитывает количество запросов ввода-вывода, которые были отправлены драйверу устройства, но еще не завершены. Он не включает запросы ввода-вывода, которые находятся в очереди, но еще не отправлены драйверу устройства.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_name: iops_in_progress",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "iops_in_progress" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "disk I/O reads/writes merged",
     "type": "graph",
     "description": "Смежные операции чтения и записи могут быть объединены для повышения эффективности. Таким образом, два чтения 4K могут превратиться в одно чтение 8K, прежде чем оно в конечном итоге будет передано на диск, и поэтому оно будет засчитано (и поставлено в очередь) как только один ввод-вывод. Эти поля позволяют узнать, как часто это делалось.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_name: merged_reads",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "merged_reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_name: merged_writes",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "select": [
        [
         { "params": [ "merged_writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" },
         { "params": [ " " ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "processes (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/processes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "processes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "kernel (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/kernel)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "kernel",
     "type": "graph",
     "description": "- entropy_avail - Содержит значение доступной энтропии\n- interrupts - В этой строке показано количество обработанных прерываний с момента загрузки для каждого из возможные системные прерывания.\n- context_switches - Количество переключений контекста, которым подверглась система.\n- boot_time - Время загрузки в секундах с начала 1970-01-01 00:00:00 +0000 (UTC).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "kernel",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "temp (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/temp)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "temp",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "sensor" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "temp",
       "select": [
        [
         { "params": [ "temp" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}