homeassistant:
  name: homea-ssistant
  latitude: "55.750095"
  longitude: "37.615611"
  elevation: "156"
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include_dir_merge_named blocks/customize
  packages: !include_dir_merge_named blocks/packages
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
     api_password: "ahcajah2Kab3ei"

# Ручная конфигурация
# Отображение панели настроек в интерфейсе
config:
# Сканирование доступных устройств в сети
ssdp:
# Включение карты
map:
# Включение поддержки приложения
mobile_app:
# Отслеживание солнца
sun:
# API для предоставления информации о системе и ее компонентах
system_health:
# Сенсор для отображения последней версии НА
updater:
# Потоковое изображение с камер
stream:
# Включение истории
history:
# Включение журнала
logbook:

lovelace:
  mode: yaml

# Text to speech
tts:
  - platform: google_translate

# Читай эти блоки из других файлов
recorder: !include blocks/recorder.yaml # База данных
api: !include blocks/api.yaml # https://www.home-assistant.io/integrations/api/
input_select: !include blocks/input_select.yaml # https://www.home-assistant.io/integrations/input_select/
device_tracker: !include blocks/device_tracker.yaml # https://www.home-assistant.io/integrations/device_tracker/
notify: !include blocks/notify.yaml # https://www.home-assistant.io/integrations/notify/
mqtt: !include blocks/mqtt.yaml # https://www.home-assistant.io/integrations/mqtt/
prometheus: !include blocks/prometheus.yaml # https://www.home-assistant.io/integrations/prometheus/
group: !include blocks/group.yaml # https://www.home-assistant.io/integrations/group/
script: !include blocks/script.yaml # https://www.home-assistant.io/integrations/script/
scene: !include blocks/scene.yaml # https://www.home-assistant.io/integrations/scene/
weather: !include blocks/weather.yaml # https://www.home-assistant.io/integrations/weather/

# Читай эти блоки из других файлов (весь каталог)
sensor: !include_dir_merge_list blocks/sensor # https://www.home-assistant.io/integrations/sensor/