filebeat.inputs:
- type: docker
  tags: ["containers"]
  combine_partial: true
  containers:
    path: "/var/lib/docker/containers"
    ids:
      - "*"
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

- type: log
  tags: ["servers"]
  paths:
    - /log/system/*.log
    - /log/system/syslog
  processors:
    - add_host_metadata: ~

output.logstash:
  hosts: ["logstash.serverhome.home:5044"]