{
 "title": "telegraf self",
 "description": "https://docs.wavefront.com/telegraf.html",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM system WITH KEY=\"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "internal agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "gather errors",
     "type": "graph",
     "description": "Сводная статистика ошибок по всем плагинам Telegraf",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: gather_errors",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "gather_errors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "metrics dropped",
     "type": "graph",
     "description": "Сводная статистика по отброшенным метрикам по всем плагинам Telegraf",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: metrics_dropped",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "metrics_dropped" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "metrics",
     "type": "graph",
     "description": "- metrics_gathered - Сводная статистика собранных метрик, по всем плагинам Telegraf\n- metrics_written - Сводная статистика для записанных метрик, для всех плагинов Telegraf",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: metrics_gathered",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "metrics_gathered" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: metrics_written",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_agent",
       "select": [
        [
         { "params": [ "metrics_written" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "internal gather",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "errors",
     "type": "graph",
     "description": "Сводная статистика ошибок по плагинам, которые имеют один и тот же тип ввода",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: errors",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_gather",
       "select": [
        [
         { "params": [ "errors" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "gather time ns",
     "type": "graph",
     "description": "Сводная статистика времени сбора данных по всем входным плагинам, которые имеют один и тот же тип ввода",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "alias": "$tag_host: gather_time_ns",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_gather",
       "select": [
        [
         { "params": [ "gather_time_ns" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "metrics gathered",
     "type": "graph",
     "description": "Сводная статистика для собранных метрик по всем плагинам, которые имеют один и тот же тип ввода",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: metrics_gathered",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_gather",
       "select": [
        [
         { "params": [ "metrics_gathered" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "internal memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes",
     "type": "graph",
     "description": "Количество выделенных байтов",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: alloc_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "alloc_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "frees",
     "type": "graph",
     "description": "Количество освобожденных байтов",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: frees",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "frees" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "heap",
     "type": "graph",
     "description": "- heap_alloc_bytes - Байты, выделенные объектам кучи\n- heap_idle_bytes - Байты в свободных диапазонах. В холостых диапазонах нет объектов. Эти промежутки могут быть возвращены в ОС, или они могут быть повторно использованы для выделения кучи, или они могут быть повторно использованы в качестве памяти стека.\n- heap_in_use_bytes - Байты в используемых диапазонах. В используемых диапазонах есть хотя бы один объект.\n- heap_objects - Количество выделенных объектов кучи. Увеличивается по мере выделения объектов и уменьшается по мере очистки кучи и освобождения недоступных объектов.\n- heap_released_bytes - Байты физической памяти возвращены в ОС. Это подсчитывает память кучи из незанятых интервалов, которая была возвращена в ОС и еще не была повторно использована для кучи.\n- heap_sys_bytes - Байты памяти кучи, полученные от ОС (объем виртуального адресного пространства, зарезервированного для кучи).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: heap_alloc_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_alloc_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: heap_idle_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_idle_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: heap_in_use_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_in_use_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: heap_objects",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_objects" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: heap_released_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_released_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      },
      {
       "alias": "$tag_host: heap_sys_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "heap_sys_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "mallocs",
     "type": "graph",
     "description": "Совокупное количество выделенных объектов кучи",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: mallocs",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "mallocs" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "num gc",
     "type": "graph",
     "description": "Количество завершенных циклов GC",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: num_gc",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "num_gc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "pointer lookups",
     "type": "graph",
     "description": "Количество поисков указателей, выполняемых средой выполнения",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: pointer_lookups",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "pointer_lookups" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "sys bytes",
     "type": "graph",
     "description": "Всего байт памяти, полученной от ОС",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: sys_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "sys_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "total alloc bytes",
     "type": "graph",
     "description": "Байты выделенных объектов кучи.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: total_alloc_bytes",
       "groupBy": [
        { "params": [ "10s" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "internal_memstats",
       "select": [
        [
         { "params": [ "total_alloc_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "internal write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "buffer limit",
   "type": "graph",
   "description": "Сводная статистика об ограничении буфера записи для всех модулей вывода с одинаковым типом ввода.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: buffer_limit",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "buffer_limit" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "buffer size",
   "type": "graph",
   "description": "Сводная статистика о размере буфера записи для всех модулей вывода с одинаковым типом ввода.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: buffer_size",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "buffer_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "metrics",
   "type": "graph",
   "description": "- metrics_added - Сводная статистика о метриках, добавленных для всех подключаемых модулей вывода с одинаковым типом ввода.\n- metrics_dropped - Сводная статистика о метриках, отброшенных для всех выходных плагинов с одним и тем же типом ввода.\n- metrics_filtered - Сводная статистика о метриках, отброшенных для всех выходных плагинов с одним и тем же типом ввода.\n- metrics_written - Сводная статистика о метриках, записанных для всех модулей вывода с одинаковым типом ввода.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: metrics_added",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "metrics_added" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host: metrics_dropped",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "metrics_dropped" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host: metrics_filtered",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "metrics_filtered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$tag_host: metrics_written",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "metrics_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "write time ns",
   "type": "graph",
   "description": "Сводная статистика о времени записи для всех выходных плагинов с одним и тем же типом ввода.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_host: write_time_ns",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "write_time_ns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}