telegram:
  sensor:
    - platform: template
      sensors:
        unavailable_now_sensor:
          friendly_name: "Всего недоступно сенсеров - "
          entity_id:
            - sersor.time
          value_template: "{{states.sensor | selectattr ('state', 'equalto', 'unavailable') | list | length}}"
          icon_template: mdi:counter

  script:
    send_message_1:
      alias: Отправка через сервис уведомлений
      sequence:
        - service: notify.privat
          data:
            message: "Текущее время - {{ states('sensor.time') }} . Все в порядке"

    system_report:
      alias: Отправка отчета о состоянии системы # http://unicode.org/emoji/charts/full-emoji-list.html тут смайлики
      sequence:
        - service: notify.privat
          data:
            message: |
                {{"\U0001F600"}} Состояние системы
                {{"\U0001F602"}} Отчет за {{ states('sensor.date_time') }}
                {{"\U0001F910"}} Сенсоров не доступно - {{ states('sensor.unavailable_now_sensor') }}

  automation:
    - id: Отчет при запуске системы
      alias: start_message
      initial_state: true
      trigger:
        - platform: homeassistant
          event: start
      action:
        - service: notify.privat
          data:
            message: |
                 Сервер gandalf.serverhome.home
                 Зафиксирован запуск службы homeassistant в {{ states('sensor.date_time') }}
                 Отчет о состоянии будет через 1 минуту
        - delay: 00:01:00
        - service: script.turn_on
          entity_id: script.system_report

    - id: Погода
      alias: weather_everyday
      initial_state: true
      trigger:
        - platform: time
          at: "09:00:00"
      condition:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
      action:
        - service: notify.group
          data:
            message: |
                 Доброе утро, сейчас {{ states('sensor.date_time') }}
                 За окном {{ states('weather.gismeteo') }}
                 Температура {{ states('sensor.homeassistant_1_temperature') }} °C
                 Влажность {{ states('sensor.homeassistant_1_humidity') }} %
                 Скорость ветра {{ states('sensor.homeassistant_1_wind_speed') }} м/с

    - id: Уведомление о протечке
      alias: notify_send_like_on
      initial_state: true
      trigger:
        - platform: state
          entity_id: sensor.aqara_water_leak_sensor_1_water_leak
          to: 'True'
      action:
        - service: notify.group
          data:
            message: |
                {{"\U0001F4A6"}} ВНИМАНИЕ ПРОТЕЧКА НА КУХНЕ

    - id: Уведомление о нехватке воды в увлажнителе
      alias: notify_send_like_on
      initial_state: true
      trigger:
        - platform: numeric_state
          entity_id: sensor.humidifier_1_depth
          above: 0
          below: 20
      action:
        - service: notify.group
          data:
            message: |
                {{"\U0001F630"}} Залей в увлажнитель водичку пжлст
        - delay: 00:30:00
