title: Датчики
icon: mdi:leak
cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.aqara_water_leak_sensor_1_water_leak
                    name: Протечка

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: sensor.humidifier_1_humidity
                  - entity: sensor.aqara_water_leak_sensor_1_battery_2
                  - entity: sensor.humidifier_1_temperature